### ISSUE TITLE
[types section]: Add note about `Int` boundaries in real life

### ISSUE THREAD

**Issue by nodkz** [graphql-rules/graphql-rules#1]
Add here: https://github.com/graphql-rules/graphql-rules/tree/master/docs/rules/02-type
Author: Andrii Chyzh @andriichyzh : https://user-images.githubusercontent.com/1946920/59221573-6c2c6380-8be9-11e9-877e-833d40202924.png

Translated version:

## Be careful with Int type

- This is `signed 32-bit integer`
- If the integer interval value represents a value less than `-2^31` or greater than or equal `2^31`, a field **error should be raised**.
- In numbers: **-2'147'483'648 / 2'147'483'647**

### This numbers in real life

- Time (in milliseconds): **~24.86 days**
- Data Volume (in bytes): **~2.15 Gb**

If you return from backend or client pass via argument a value which greater - you'll get an ERROR.

**Comment by nodkz** [comment]
Does anybody want to write a rule for site?

**Comment by IvaTsu** [comment]
@nodkz, I think I can inject the above description about `Int` limitations into the type rules if it is still relevant. Please let me know and I will send a new PR.

**Comment by nodkz** [comment]
@IvaTsu sure!

It will be amazing 👍

**Comment by IvaTsu** [comment]
@nodkz, here is PR #100 related to this topic.
