### ISSUE TITLE
[naming-enum] avoid using too many _ underscore's together, as it get all italics and it's a mess.

### ISSUE THREAD

**Issue by agustif** [graphql-rules/graphql-rules#10]
I'm guessing this is due to Markdown interpeting the ```_word_``` as _italic_

<img width="846" alt="Screenshot 2019-06-24 at 17 16 15" src="https://user-images.githubusercontent.com/6601142/60030773-df32e100-96a3-11e9-81e6-7283ebe55e73.png">

**Comment by nodkz** [comment]
Thanks for reporting! 🙏

Should be fixed somewhere in Gatsby remarker (transpiler).

Source page: https://github.com/graphql-rules/graphql-rules/blob/master/docs/rules/01-naming/naming-enum.md
Site page: https://graphql-rules.com/rules/naming-enum

**Comment by nodkz** [comment]
As a workaround, now fixed via codeblocks (``).
