### ISSUE TITLE
Background and more information about the mutation payload query rule

### ISSUE THREAD

**Issue by rocketraman** [graphql-rules/graphql-rules#61]
I just read https://graphql-rules.com/rules/mutation-payload-query. This is an interesting approach which kind of boggled my mind when I read it -- it upset, in a good way, my whole thinking about what a GraphQL mutation could do vs an equivalent regular RPC.

That being said, it still bothers me a bit that a mutation would allow a user to query for data completely unrelated to the mutation they requested.

Can someone explain the real-world experience / background that led to the creation of this rule? I'd be interested in understanding the use cases not already presented in the rule text, if any, and alternative approaches considered, such as simply ensuring that the schema mutation exposes the changed fields in the payload, instead of the entire query.

**Comment by rocketraman** [comment]
Relevant discussion about this here: https://github.com/ExpediaGroup/graphql-kotlin/discussions/1169#discussioncomment-804023.

**Comment by rocketraman** [comment]
Quote:

> But even as called out in the website you posted, it appears magically, and to us that is an anti-pattern of a schema-based API where everything is explicitly defined and the execution code is a 1-1 mapping. We could support this but we think this is actually a strong enough anti-pattern that we do not even want to have the ability, so it is not encouraged.
> 
> The spec calls out that the Root Operation Types define the types available to the root of the operation
https://spec.graphql.org/draft/#sec-Root-Operation-Types
> 
> Instead we encourage schema developers to think about the data clients need in the mutation response so they don't have to make another round trip and return that data, but not the entire Query object. That will ensure the data returned is updated properly by mutation code and there are no other issues with caches and data loaders on other top level fields, as those should be run as a separate operation.

**Comment by nodkz** [comment]
> That being said, it still bothers me a bit that a mutation would allow a user to query for data completely unrelated to the mutation they requested.

The mutation is an operation of changing the server state. So why not provide an easy way for clients (frontend developers) to get a newly updated state in the one round-trip? And `query` field in the mutation payload provides such ability.

> alternative approaches considered, such as simply ensuring that the schema mutation exposes the changed fields in the payload

Why alternative? It can be a complementary way of obtaining a server state. You may provide both of these approaches in your schema and only the client (frontend developer) decides how he wants to receive a response. 

GraphQL Schema announces its capabilities, the client declares its needs. If you announce fewer capabilities, the client will be forced to use only what you provide. GraphQL was designed to give clients the power to ask for exactly what they need. And if the client can obtain required data in many ways, the client definitely chooses the easier and comfortable way. And in different cases will be used different ways. The most powerful side of GraphQL that clients decide how they want to get the required data. 

> The spec calls out that the Root Operation Types define the types available to the root of the operation
https://spec.graphql.org/draft/#sec-Root-Operation-Types

Yep, spec calls out to provide 3 Object Types as entry points for your graph. BUT it does not prohibit reusing eg Query type inside mutation payloads.

I don't want to argue that this approach is an anti-pattern. I showed a fairly simple method that allows clients to query the server state after a data change operation. Whether or not it is up to you to provide such ability to your clients. But definitely, you should not block this feature.

If you are not sure about this feature then just take a pause! Gather more votes about this feature, listen to your client requirements.
