### ISSUE TITLE
Some content is still in Russian.

### ISSUE THREAD

**Issue by wtrocki** [graphql-rules/graphql-rules#8]
https://graphql-rules.com/rules/output-semantic-names

**Comment by nodkz** [comment]
Thanks for pointing.

We already got tech writer review for current rules and they will be fixed in a week or two. We can work under the site only in free time right now. 

Sorry for our slowness 😉

**Comment by RIP21** [comment]
@wtrocki hey man. I fixed most of the issues :) Enjoy English :D If any other will be there, let me know :)

**Comment by wtrocki** [comment]
Awesome! Thank you so much!
