### ISSUE TITLE
Mention or reference graphql-eslint

### ISSUE THREAD

**Issue by Urigo** [graphql-rules/graphql-rules#80]
I always love this amazing resource you created @nodkz 

A lot of rules suggestions we get for https://github.com/dotansimha/graphql-eslint are based on this great resource.

I wonder if it would be helpful for readers of this to know that they could also enforce some of these rules using graphql-eslint?

**Comment by blep** [comment]
Shouldn't this be closed? It is now referenced in the appendix:
https://graphql-rules.onrender.com/rules/appendix/#A-1

**Comment by RIP21** [comment]
@blep makes sense. Closing it.
