### ISSUE TITLE
Avoid using `get` in your @GraphQL schemas

### ISSUE THREAD

**Issue by nodkz** [graphql-rules/graphql-rules#9]
By @sibelius

Avoid using `get` in your @GraphQL schemas

for instance:

post {
   getLikedByUsers(first: Int)
}

prefer this:

post {
   likedByUsers(first: Int)
}

drop the REST naming

https://twitter.com/sseraphini/status/1141758041731284993?s=19

**Comment by nodkz** [comment]
Does anybody want to write a rule according to this proposal?

**Comment by IvaTsu** [comment]
Hey, @nodkz, I would like to write it if it is still relevant. Please let me know and I will send a PR for that.
And if so, do you think the `Naming rules` is a good place for that?

**Comment by nodkz** [comment]
Avoid using get in your Query resolvers.
But keep action verbs in Mutations - like delete, create.

Let's do it under the Naming rules. It's a good suggestion 👍

**Comment by IvaTsu** [comment]
@nodkz, here is PR #101 related to this topic.
